ckb-js/ckb-sdk-js

packages/ckb-sdk-rpc/src/defaultRPC.ts
Add rpc of getBlockByNumber which requires blockNumber as an input and returns a block promise.
ref: https://github.com/nervosnetwork/ckb/pull/631/files
=> feat(rpc): add rpc of getBlockByNumber

README.md, packages/ckb-types/index.d.ts
'lock or unlock' script => 'lock or type' script
=> [ᚬrc/v0.11.0] docs: fix typo in readme and type comments

README.md, packages/ckb-types/index.d.ts
'lock or unlock' script => 'lock or type' script
=> docs: fix typo in readme and type comments

README.md, lerna.json, packages/ckb-cli/package.json, packages/ckb-sdk-address/package.json, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-utils/__tests__/ckb-utils.test.js, packages/ckb-sdk-utils/package.json, packages/ckb-sdk-utils/src/index.ts, packages/ckb-types/package.json
1. merge fixes from rc/v0.11.0
1. rename binaryHash to codeHash in a utils method
2. slight update in README
2. merge version update from rc/v0.11.0 which is 0.11.0-alpha.0 now.
=> merge fixes from rc/v0.11.0

.gitignore
Ignore the generated package-lock.json in CI, which stopped Buiding.
Ref: https://travis-ci.com/nervosnetwork/ckb-sdk-js/jobs/199900988#L692
=> [ᚬmaster] ci: ignore package-lock.json for deploy docs

.travis.yml
> Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created
during the build, which will probably delete what you are trying to upload.
=> [ᚬmaster] ci: keep temp dir for building docs on deploying gh-pages

.gitignore, .travis.yml, CHANGELOG.md, README.md, lerna.json, packages/ckb-cli/CHANGELOG.md, packages/ckb-cli/README.md, packages/ckb-cli/package.json, packages/ckb-sdk-address/CHANGELOG.md, packages/ckb-sdk-address/README.md, packages/ckb-sdk-address/package.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/README.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/README.md, packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/README.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/README.md, packages/ckb-types/package.json
1. merge v0.11.0 to develop branch
2. remove wallet module which has been removed in the current develop branch but imported by v0.11.0
3. remove redundant test cases which imported by v0.11.0
=> merge the released v0.11.0 to develop branch

packages/ckb-sdk-core/src/index.ts, packages/ckb-sdk-utils/__tests__/ckb-utils.test.js, packages/ckb-sdk-utils/src/address/index.ts
replace the default address prefix from `ckb` to `ckt`, which is the signal of testnet.
=> feat(utils): set 'ckt' as the default prefix of addresses

packages/ckb-sdk-core/examples/sendTransaction.js
fix the get unspent cells method
`getUnspentCells` returns cells from [from, to] inclusively, so the next iteration should start from `to+1`
=> docs(core): fix the example of sending transactions

CHANGELOG.md, lerna.json, packages/ckb-cli/CHANGELOG.md, packages/ckb-cli/package.json, packages/ckb-sdk-address/CHANGELOG.md, packages/ckb-sdk-address/package.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/__tests__/formatters/params.test.js, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-rpc/src/defaultRPC.ts, packages/ckb-sdk-rpc/src/paramsFormatter.ts, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/index.d.ts, packages/ckb-types/package.json
* **rpc:** add a parser for optional parameters ([274268e](https://github.com/nervosnetwork/ckb-sdk-js/commit/274268e))
* **rpc:** update the returned cell type of getLiveCell from cell to liveCell ([4a69d85](https://github.com/nervosnetwork/ckb-sdk-js/commit/4a69d85))
=> [ᚬmaster] Rc/v0.21.1

packages/ckb-sdk-rpc/__tests__/formatters/params.fixtures.json, packages/ckb-sdk-rpc/__tests__/formatters/params.test.js, packages/ckb-sdk-rpc/src/paramsFormatter.ts
allow bigit and forbid number type
BREAKING CHANGE: use bigint instead of number in the interfaces of rpc methods
=> feat(rpc): use bigint instead of number in the interfaces of rpc methods

packages/ckb-sdk-core/src/address.ts, packages/ckb-sdk-core/src/index.ts, packages/ckb-sdk-utils/__tests__/utils/index.test.js, packages/ckb-sdk-utils/src/address/index.ts, packages/ckb-sdk-utils/src/crypto/bech32.ts
1. add a new method to generate full version addresses
2. rename an parameter in bech32Address method from codeHashIndex to codeHashOrCodeHashIndex
BREAKING CHANGE: rename an parameter in bech32Address method from codeHash to codeHashOrCodeHashIndex
=> feat(address): add support to addresses in full version format

CHANGELOG.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/__tests__/loadCells/fixtures.json, packages/ckb-sdk-core/__tests__/loadCells/index.test.js, packages/ckb-sdk-core/package.json, packages/ckb-sdk-core/src/index.ts, packages/ckb-sdk-core/src/loadCells.ts, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-rpc/src/defaultRPC.ts, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/package.json
* **rpc:** update the signatures of rpc methods ([7eb6726](https://github.com/nervosnetwork/ckb-sdk-js/commit/7eb6726)), closes [#365](https://github.com/nervosnetwork/ckb-sdk-js/issues/365)
* **rpc:** use bigint instead of number in signatures of rpc methods
=> [ᚬmaster] Rc/v0.22.1

packages/ckb-sdk-core/types/global.d.ts
fixed a misstyping from 'CKBComponent' to 'CKBComponents'
fixed type mismatch between CachedCell.type and CellOutput.type
=> add the missing 's' to 'CKBComponent.Script'

packages/ckb-sdk-utils/__tests__/ecpair/ecpare.fixtures.json, packages/ckb-sdk-utils/__tests__/ecpair/index.test.js, packages/ckb-sdk-utils/src/ecpair.ts
1. check the length of provided private key. 2. remain leading 0 of private key.
=> refactor(utils): refine ECPair

CHANGELOG.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/package.json
**Note:** Version bump only for package ckb-sdk-js
=> [ᚬmaster] Rc/v0.27.0

CHANGELOG.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/package.json
**Note:** Version bump only for package ckb-sdk-js
=> [ᚬmaster] chore: update package versions and changelogs

CHANGELOG.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-rpc/src/defaultRPC.ts, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/package.json
* **rpc:** update the action of outputs validator when it is null ([4932c47](https://github.com/nervosnetwork/ckb-sdk-js/commit/4932c479141b6d7a109705c389290b66d67c83a2))
* **rpc:** null outputs validator is equivalent to the passthrough one
=> [ᚬmaster] rc/v0.29.0

README.md, packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json, packages/ckb-sdk-rpc/src/defaultRPC.ts, packages/ckb-sdk-rpc/src/resultFormatter.ts, packages/ckb-sdk-rpc/types/rpc/index.d.ts, packages/ckb-types/index.d.ts
The new RPC returns the increased issuance, miner reward and total transaction fee of the specified block
=> [ᚬrc/v0.30.0] feat(rpc): add the new RPC getBlockEconomicState

CHANGELOG.md, README.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js, packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-rpc/src/defaultRPC.ts, packages/ckb-sdk-rpc/src/resultFormatter.ts, packages/ckb-sdk-rpc/types/rpc/index.d.ts, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/index.d.ts, packages/ckb-types/package.json, yarn.lock
* **rpc:** add a new field in the tx pool info ([c1cbac9](https://github.com/nervosnetwork/ckb-sdk-js/commit/c1cbac9aeb1799f611543696f7ee9b717cfb237d))
* **rpc:** add the new RPC getBlockEconomicState ([0c9e248](https://github.com/nervosnetwork/ckb-sdk-js/commit/0c9e248d810dcbe83953f262385b4a8efb5d4f84))
=> [ᚬmaster] Rc/v0.30.0

packages/ckb-sdk-core/__tests__/signWitnesses/fixtures.json, packages/ckb-sdk-core/__tests__/signWitnesses/index.test.js, packages/ckb-sdk-core/src/index.ts, packages/ckb-sdk-core/src/signWitnessGroup.ts, packages/ckb-sdk-core/src/signWitnesses.ts
A signature provider is a function that maps a message to signature. Use the signature provider to sign transactions can facilitate the integration of 3rd-party keypair manager when using the sdk.
To sign a transaction now, use
``` js
const signedWitnesses = signWitnesses(signatureProviderMap)({
transactionHash,
witnesses,
inputCells,
skipMissingKeys,
})
```
`signatureProviderMap` is a `Map<LockHash, SignatureProvider>` or a single `SignatureProvider`. A `SignatureProvider` can be either a plain string for a private key, or a function
``` js
function sigProvider (message: string) : string {
// Possible code inside the 3rd-party keypair manager
const privateKey = ThirdPartyKeypairManager.loadPrivateKey()
const keyPair = new ECPair(privateKey)
return keyPair.signRecoverable(message)
}
``` …
=> feat: use signature provider in signWitnesses & signWitnessGroup

package.json, packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js, packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json, packages/ckb-sdk-rpc/src/Base.ts, packages/ckb-sdk-rpc/src/index.ts, packages/ckb-sdk-rpc/src/resultFormatter.ts, packages/ckb-sdk-rpc/types/rpc/index.d.ts, packages/ckb-types/index.d.ts, yarn.lock
1. fix the return type of `rpc.getLiveCellsByLockHash` by adding two missing fields of `cellbase` and `outputDataLen`;
2. refactor the default rpc list to make it clear;
3. add two npm scripts to build/clean libs;
=> Fix rpc api

README.md, codecov.yaml, packages/ckb-sdk-core/__tests__/signWitnessGroup/fixtures.json, packages/ckb-sdk-core/__tests__/signWitnessGroup/index.test.js, packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js, packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js, packages/ckb-sdk-rpc/__tests__/formatters/params.fixtures.json, packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json, packages/ckb-sdk-rpc/__tests__/method.test.js, packages/ckb-sdk-rpc/src/Base.ts, packages/ckb-sdk-rpc/src/index.ts, packages/ckb-sdk-rpc/src/method.ts
1. Add an API for batch request
2. Remove the method property from class CKBRPC
BREAKING CHANGE: 1. Add an API for batch request
re #438
=> feat(rpc): enable batch request

README.md
Remove sdk-lumos-starter repo from docs since an example of how to use lumos with sdk has been added
in examples
=> docs: remove sdk-lumos-starter from docs

packages/ckb-sdk-core/__tests__/fixtures.json, packages/ckb-sdk-core/__tests__/generateRawTransaction/fixtures.json, packages/ckb-sdk-core/__tests__/generateRawTransaction/index.test.js, packages/ckb-sdk-core/__tests__/index.test.js, packages/ckb-sdk-core/src/generateRawTransaction.ts, packages/ckb-sdk-core/src/index.ts, packages/ckb-sdk-core/types/global.d.ts
This commit enables parsing scripts from addresses on generating a transaction, instead of using the
default secp256k1/blake160 script.
But the lock script in change output is fixed to the default secp256k1/blake160 script.
FWIW, the internal interface `generateRawTransaction` in core/generateRawTransaction is changed to accept scripts instead of public key hash.
=> feat(core): parse scripts from addresses on generating transactions

.eslintrc.js, packages/ckb-sdk-utils/__tests__/crypto/blake2b.test.js, packages/ckb-sdk-utils/src/crypto/blake2b.ts, packages/ckb-sdk-utils/tsconfig.json
This commit prevents `blake2b-wasm` from being loaded when it's iOS 11.
=> feat: disable blake2b-wasm when the host is iOS 11

packages/ckb-sdk-utils/__tests__/crypto/blake2b.test.js, packages/ckb-sdk-utils/package.json, packages/ckb-sdk-utils/src/crypto/blake2b.ts, yarn.lock
Remove explicit support of blake2b-wasm since it's not used in any projects while  blake2b-wasm@v1.1.0 is used implicitly by blake2b.
BREAKING CHANGE: Remove explicit support of blake2b-wasm@v2.1.0
=> feat(utils): remove support of blake2b-wasm@v2.1.0

packages/ckb-sdk-core/__tests__/generateRawTransaction/fixtures.json, packages/ckb-sdk-core/src/generateRawTransaction.ts, packages/ckb-sdk-core/types/global.d.ts
This commit replaces the `change public key hash` in `generateRawTransaction` with `change lock
script` so the change lock script is not bound to secp256k1 lock script.
BREAKING CHANGE: `changePublicKeyHash` in `generateRawTransaction` is replaced with
`changeLockScript`
=> fix(core): use change lock script instead of change public key hash

README.md
Using ckb-indexer or lumos instead of the deprecated indexer module
=> docs: indexer module is deprecated

CHANGELOG.md, README.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js, packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js, packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-rpc/src/Base/chain.ts, packages/ckb-sdk-rpc/src/Base/index.ts, packages/ckb-sdk-rpc/src/Base/pool.ts, packages/ckb-sdk-rpc/src/resultFormatter.ts, packages/ckb-sdk-rpc/types/rpc/index.d.ts, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/README.md, packages/ckb-sdk-utils/package.json, packages/ckb-sdk-utils/src/address/index.ts, packages/ckb-types/CHANGELOG.md, packages/ckb-types/index.d.ts, packages/ckb-types/package.json, yarn.lock
* **rpc:** add rpc#getRawTxPool, rpc#getConsensus and deprecate rpc#getCellbaseOutputCapacityDetails, rpc#getPeersState ([#528](https://github.com/nervosnetwork/ckb-sdk-js/pull/528))
=> Release v0.39.0

CHANGELOG.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/package.json, yarn.lock
**Note:** Version bump only for package ckb-sdk-js
=> Release 0.41.0

CHANGELOG.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/package.json
**Note:** Version bump only for package ckb-sdk-js
=> Release v0.102.3

packages/ckb-sdk-utils/__tests__/address/fixtures.json, packages/ckb-sdk-utils/src/address/index.ts
1. when address type is hash index, default code hash index
should be secp256k1 code hash index
2. when address type is not hash index, default code hash
should be secp256k1 code hash
3. when code hash is secp256k1, default hash type should be
type
Ref: https://github.com/nervosnetwork/ckb-sdk-js/issues/586
=> fix: fix default code hash/code hash index in toAddressPayload

packages/ckb-sdk-utils/__tests__/address/fixtures.json, packages/ckb-sdk-utils/__tests__/exceptions/fixtures.json, packages/ckb-sdk-utils/src/address/index.ts, packages/ckb-sdk-utils/src/exceptions/address.ts
1. refactor utils.addressToScript for robustness
2. bech32m is required when address format type is 0x00
3. bech32 is required when address format type in [0x01, 0x02, 0x04]
4. limit address format type to 0x00, 0x01, 0x02, 0x04 in deprecated address generating method.
=> reinforce restriction of generating and parsing address

CHANGELOG.md, README.md, lerna.json, packages/ckb-sdk-core/CHANGELOG.md, packages/ckb-sdk-core/README.md, packages/ckb-sdk-core/package.json, packages/ckb-sdk-core/src/index.ts, packages/ckb-sdk-rpc/CHANGELOG.md, packages/ckb-sdk-rpc/README.md, packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js, packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js, packages/ckb-sdk-rpc/package.json, packages/ckb-sdk-rpc/src/Base/index.ts, packages/ckb-sdk-rpc/src/Base/stats.ts, packages/ckb-sdk-rpc/types/rpc/index.d.ts, packages/ckb-sdk-utils/CHANGELOG.md, packages/ckb-sdk-utils/README.md, packages/ckb-sdk-utils/package.json, packages/ckb-types/CHANGELOG.md, packages/ckb-types/README.md, packages/ckb-types/index.d.ts, packages/ckb-types/package.json
- refactor: update RPC name of `get_fee_rate_statistics`, ref: https://github.com/nervosnetwork/ckb/pull/3924
=> Release v0.109.0

packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js, packages/ckb-sdk-rpc/src/index.ts
Short circuit batch request with an empty array if request payload is an empty array
Ref: https://github.com/ckb-js/ckb-sdk-js/issues/615
=> fix: return empty array if payload of batch request is an empty array

package-lock.json, package.json
`axios` has been updated by https://github.com/ckb-js/ckb-sdk-js/pull/649 which uses esmodule and not compatible with jest.
This PR bumps `cross-spawn` and fixes the incompatibility between axios and jest.
=> feat: bump dependencies and fix tests for incompatibility
