ckb-js/ckb-sdk-js

.editorconfig
.eslintrc.js
.travis.yml
makefile
package.json
packages/ckb-core/__tests__/ckb-core.test.js
packages/ckb-rpc/__tests__/ckb-rpc.test.js
packages/ckb-rpc/src/defaultRPC.ts
packages/ckb-rpc/tsconfig.json
packages/ckb-utils/__tests__/ckb-utils.test.js
packages/ckb-wallet/__tests__/ckb-wallet.test.js
yarn.lock

[Setup CI](https://github.com/nervosnetwork/ckb-sdk-js/issues/22)

update tests and remove test from CI until ckb docker is set

---

packages/ckb-sdk-utils/__tests__/ckb-utils.test.js
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-utils/src/crypto.ts
packages/ckb-sdk-utils/src/index.ts
packages/ckb-sdk-utils/tsconfig.json
packages/ckb-sdk-utils/types/blake2b-wasm/index.d.ts
packages/ckb-sdk-utils/types/sha3/index.d.ts
packages/ckb-sdk-wallet/src/alwaysSuccessAccount.ts

BREAKING CHANGE: update default signature method

feat(utils): repalce-sha3-with-blake2b

---

.gitmodules
packages/ckb-sdk-wallet/package.json
packages/ckb-sdk-wallet/src/UDTAccount.ts

- remove ruby contract
- rename mrubyCell to tokenCell

Remove unlock ruby

---

packages/ckb-sdk-rpc/src/defaultRPC.ts
packages/ckb-sdk-rpc/src/paramsFormatter.ts
packages/ckb-sdk-wallet/src/account.ts
packages/ckb-sdk-wallet/src/alwaysSuccessAccount.ts
packages/ckb-types/index.d.ts

BREAKING CHANGE: replace type of u64 with type of string in ckb-types, remove version field from script interface

feat(types): update ckb-types

---

packages/ckb-sdk-rpc/src/paramsFormatter.ts
packages/ckb-sdk-wallet/src/account.ts
packages/ckb-types/index.d.ts

BREAKING CHANGE: rpc interface updated, add field of validSince in cell input of a transaction

feat(types): add field of validSince in cell input of a transaction

---

packages/ckb-sdk-rpc/src/paramsFormatter.ts
packages/ckb-sdk-wallet/src/account.ts
packages/ckb-types/index.d.ts

1. set the type of validSince to string
2. rename prevOutput to previousOutput

merge a patch from rc/v0.10.0

---

packages/ckb-sdk-rpc/src/paramsFormatter.ts
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-utils/src/index.ts
packages/ckb-sdk-wallet/src/account.ts
packages/ckb-sdk-wallet/src/alwaysSuccessAccount.ts
packages/ckb-types/index.d.ts

https://github.com/nervosnetwork/neuron/issues/264

batch rpc interface updates

---

CHANGELOG.md
lerna.json
packages/ckb-cli/CHANGELOG.md
packages/ckb-cli/package.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/package.json
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-wallet/CHANGELOG.md
packages/ckb-sdk-wallet/package.json
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json

fix conflicts to https://github.com/nervosnetwork/ckb-sdk-js/tree/master

merge rc/v0.9.1

---

packages/ckb-sdk-rpc/src/paramsFormatter.ts
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-wallet/src/alwaysSuccessAccount.ts
packages/ckb-types/index.d.ts

rename `hash` to `tx_hash` in OutPoint type

refactor(types): rename hash to tx_hash in rpc outpoint type

---

.travis.yml
packages/ckb-sdk-address/README.md
packages/ckb-sdk-address/__tests__/ckb-sdk-address.test.js
packages/ckb-sdk-address/package.json
packages/ckb-sdk-address/src/index.ts
packages/ckb-sdk-address/tsconfig.json

Add Address module.
The wallet module will be kept for now for compatibility but may be deprecated cuz its concept is fuzzy.

[ᚬrc/v0.11.0] Add address package

---

packages/ckb-cli/package.json
packages/ckb-sdk-core/package.json
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-wallet/package.json
packages/ckb-types/package.json

update hashes after publishing to npm

build: update lerna hashes

---

lerna.json
packages/ckb-cli/package.json
packages/ckb-sdk-core/package.json
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-wallet/package.json
packages/ckb-types/package.json

hotfix of v0.10.2

---

README.md
packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/__tests__/formatters/fixtures.json
packages/ckb-sdk-rpc/__tests__/formatters/result.test.js
packages/ckb-sdk-rpc/src/defaultRPC.ts
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

1. get blockchain info
2. get peers state

Get blockchain info

---

packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/src/index.ts
packages/ckb-sdk-rpc/src/method.ts

move node property and setNode method to Method Class as static properties, which makes it easy to understand.

Move node property and setNode method to Method Class as static properties

---

packages/ckb-sdk-rpc/src/defaultRPC.ts
packages/ckb-types/index.d.ts

@see https://github.com/nervosnetwork/ckb/pull/720
1. add a type of Cycle
2. add a type of RunDryResult
3. remove resultFormatter in the dryRunTransaction method.

feat(rpc): update result of dryRunTransaction from hash to { cycles }

---

packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-types/index.d.ts

fix tests of getting live cell and send transaction

fix(rpc): fix get live cell rpc

---

packages/ckb-sdk-rpc/src/resultFormatter.ts

not throw errors anymore, pass the value to the endpoint.

refactor(rpc): refactor result formatter for better null value handling

---

packages/ckb-sdk-rpc/__tests__/formatters/fixtures.json
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

update `staging` field in the tx pool info to `proposed` field

feat(rpc): update staging in tx pool info to proposed

---

packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/src/index.ts

add method of core.generateAddress(privateKey) for generating address object

feat(core): add address module into core module

---

README.md

1. add methods to generate private key
2. add lerna bootstrap related info

docs: add priv key and lerna tool info in the readme[skip ci]

---

packages/ckb-sdk-address/README.md

fix require typo

---

packages/ckb-sdk-address/README.md

Update doc issues reported by #226.

Fix address doc

---

packages/ckb-sdk-address/src/index.ts
packages/ckb-sdk-utils/src/address/index.ts
packages/ckb-sdk-utils/src/crypto/blake160.ts
packages/ckb-sdk-utils/src/ecpair.ts

add function overload on who have the encode parameter.

refactor(utils): add function overload on who have the encode parameter.

---

packages/ckb-cli/README.md
packages/ckb-cli/package.json
packages/ckb-cli/src/dashboard/index.ts
packages/ckb-cli/src/index.ts

which provides convenience developping dapps locally.

feat(cli): add dashboard mode of ckb-cli

---

packages/ckb-sdk-rpc/__tests__/formatters/fixtures.json
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

remove warnings field and add alerts field
BREAKING CHANGE: replace warnings field with alerts field in the response of get blockchain info rpc

feat(rpc): update get blockchain info rpc

---

packages/ckb-sdk-rpc/__tests__/formatters/result.json
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

remove block_reward, last_block_hash_in_previous_epoch, remainder_reward fields, add epoch_reward
field
BREAKING CHANGE: update the type of epoch, remove block_reward, last_block_hash_in_previous_epoch,
remainder_reward fields, add epoch_reward field.

feat(rpc): update the type of epoch

---

packages/ckb-sdk-utils/src/address/index.ts

remove toAddressIdentifier method, which is the alias of toAddressPayload method
BREAKING CHANGE: remove toAddressIdentifier method

feat(utils): remove toAddressIdentifier method

---

packages/ckb-sdk-rpc/src/defaultRPC.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

the return type should include the status of the transaction

fix(rpc): fix the return type of get_transaction api

---

packages/ckb-sdk-address/__tests__/ckb-sdk-address.test.js
packages/ckb-sdk-address/src/index.ts
packages/ckb-sdk-core/src/index.ts
packages/ckb-sdk-utils/__tests__/ckb-utils.test.js
packages/ckb-sdk-utils/src/address/index.ts

use the hash index instead of the binary index in the address generator
BREAKING CHANGE: update the address format

feat(utils): update the address format

---

packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js
packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/__tests__/formatters/result.json
packages/ckb-sdk-rpc/src/defaultRPC.ts
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

- get_header
- get_header_by_number
- get_cellbase-output_capacity-details
- set_ban
- get_banned_addresses

Add new rpc

---

packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

add a field of blockHash in the result of the getCellsByLockHash method
and update the type of CellIncludingOutPoint
BREAKING CHANGE: update the result of getCellsByLockHash method

feat(type): update the result of getCellsByLockHash method

---

packages/ckb-sdk-core/__mocks__/data/genesisBlock.json
packages/ckb-sdk-core/__tests__/fixtures.json
packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

1. remove unclesCount
2. merge witnessesRoot and transactionRoot
3. replace difficulty with compactTarget
BREAKING CHANGE:
1. remove unclesCount
2. merge witnessesRoot and transactionRoot
3. replace difficulty with compactTarget
Ref: https://github.com/nervosnetwork/ckb/pull/1643

feat(type): update the fields of BlockHeader

---

README.md
packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js
packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json
packages/ckb-sdk-rpc/src/defaultRPC.ts
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
packages/ckb-types/index.d.ts

add the rpc method of estimateFeeRate to get the estimated fee rate for transaction commit in
expected blocks

feat(rpc): add a rpc method

---

.eslintrc.js
.prettierrc
package.json
packages/ckb-sdk-core/src/index.ts
yarn.lock

move prettier config outside so that editor will take actions correctly
Only eslint config and type definition updated

chore: update eslint config

---

packages/ckb-sdk-core/__tests__/loadCells/index.test.js
packages/ckb-sdk-core/examples/nervosDAO.js
packages/ckb-sdk-core/src/generateRawTransaction.ts
packages/ckb-sdk-core/src/index.ts
packages/ckb-sdk-core/src/loadCells.ts
packages/ckb-sdk-core/src/signWitnessGroup.ts
packages/ckb-sdk-rpc/src/paramsFormatter.ts
packages/ckb-sdk-utils/__tests__/serialization/transaction/fixtures.json
packages/ckb-sdk-utils/__tests__/serialization/transaction/index.test.js
packages/ckb-sdk-utils/__tests__/utils/index.test.js
packages/ckb-sdk-utils/__tests__/utils/transactionFee.fixtures.json
packages/ckb-sdk-utils/__tests__/validators/fixtures.json
packages/ckb-sdk-utils/__tests__/validators/index.test.js
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-utils/src/index.ts
packages/ckb-sdk-utils/src/serialization/index.ts
packages/ckb-sdk-utils/src/validators.ts

BREAKING CHANGE: utils.toHexInLittleEndian will not accept parameters in number

feat: enable JSBI for compatibility

---

CHANGELOG.md
lerna.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/__tests__/utils/fixtures.json
packages/ckb-sdk-core/__tests__/utils/index.test.js
packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/src/index.ts
packages/ckb-sdk-core/src/utils.ts
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/package.json
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json

* **core:** fix the calculation of epoch locks in nervos dao operation ([d914007](https://github.com/nervosnetwork/ckb-sdk-js/commit/d914007fd14456217d4f4430ad4e868ca998f65d))

[ᚬmaster] Rc/v0.29.1

---

packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json
packages/ckb-sdk-rpc/src/resultFormatter.ts
packages/ckb-sdk-rpc/types/rpc/index.d.ts
packages/ckb-types/index.d.ts

add the field minFeeRate in the tx pool info

feat(rpc): add a new field in the tx pool info

---

.eslintrc.js
packages/ckb-sdk-utils/__tests__/convertors/fixtures.json
packages/ckb-sdk-utils/__tests__/convertors/index.test.js
packages/ckb-sdk-utils/src/convertors/index.ts
packages/ckb-sdk-utils/src/index.ts

add toUint16Le, toUint32Le and toUint64Le

feat(utils): add convertors of uint-to-le

---

packages/ckb-sdk-core/__tests__/fixtures.json
packages/ckb-sdk-core/__tests__/index.test.js
packages/ckb-sdk-core/__tests__/utils/fixtures.json
packages/ckb-sdk-core/__tests__/utils/index.test.js
packages/ckb-sdk-core/src/index.ts
packages/ckb-sdk-core/src/utils.ts

1. move absoluteEpochSince into utils;
2. move filterCellsByInputs into utils;
3. add a private method to validate transaction to sign

refactor(core): extract some utils

---

README.md
packages/ckb-sdk-core/README.md
packages/ckb-sdk-rpc/README.md
packages/ckb-sdk-utils/README.md
packages/ckb-types/README.md

docs: add links to type doc

---

packages/ckb-sdk-core/__tests__/fixtures.json
packages/ckb-sdk-core/__tests__/index.test.js
packages/ckb-sdk-core/src/index.ts

1. remove computeTransactionHash RPC;
2. remove computeScriptHash RPC;
BREAKING CHANGE: computeTransactionHash and computeScriptHash are removed from the rpc list

feat(core): remove experimental rpc

---

.travis.yml
codecov.yaml

1. update node versions to [12.18, 13.7, 13.14, 14.5]
2. include rpc tests in codecov

ci: update codecov config and travis config

---

.github/workflows/docs.yml
.github/workflows/snyk.yml
.github/workflows/tests.yml
README.md

Use github actions instead of travis since it misses codecov sometime.

ci: use github actions

---

.github/workflows/bundle.yml
.github/workflows/tests.yml

1. add cache of node modules
2. add a workflow of bundling

Refine GitHub actions

---

packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js
packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json
packages/ckb-sdk-rpc/src/Base/index.ts
packages/ckb-sdk-rpc/src/Base/stats.ts
packages/ckb-sdk-rpc/src/resultFormatter.ts

remove rpc#getPeersState
BREAKING CHANGE: remove rpc#getPeersState

feat(rpc): remove an RPC

---

packages/ckb-sdk-utils/__tests__/systemScripts/fixtures.json
packages/ckb-sdk-utils/__tests__/systemScripts/index.test.js
packages/ckb-sdk-utils/src/index.ts
packages/ckb-sdk-utils/src/systemScripts.ts

Add system scripts in the utils#systemScripts
ref: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0024-ckb-system-script-list/0024-ckb-system-script-list.md

feat(utils): add system scripts

---

packages/ckb-sdk-utils/__tests__/address/fixtures.json
packages/ckb-sdk-utils/src/address/index.ts

BREAKING CHANGE: Remove the utils#defaultAddressOptions

refactor(utils): remove redundant default options in the address module

---

CHANGELOG.md
lerna.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/types/global.d.ts
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/package.json
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json

* **core:** fix type declaration of RawTransactionParams ([f9ba7bf](https://github.com/nervosnetwork/ckb-sdk-js/commit/f9ba7bf7bafa399d4a259947a9ef42056c6d7594))

fix(core): fix type declaration of RawTransactionParams

---

packages/ckb-sdk-utils/__tests__/address/fixtures.json
packages/ckb-sdk-utils/__tests__/systemScripts/fixtures.json
packages/ckb-sdk-utils/__tests__/systemScripts/index.test.js
packages/ckb-sdk-utils/src/address/index.ts
packages/ckb-sdk-utils/src/systemScripts.ts

feat(utils): update acp lock script

---

README.md
package.json
packages/ckb-sdk-core/examples/sudt.js
packages/ckb-sdk-core/src/loadCellsFromIndexer.ts
yarn.lock

This commit adds a simple example to demonstrate how to issue and transfer sudt

feat: upgrade @ckb-lumos/indexer and add the example of sudt transaction

---

.github/workflows/docs.yml
CHANGELOG.md
README.md
lerna.json
package.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/examples/sudt.js
packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/src/loadCellsFromIndexer.ts
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/__tests__/address/fixtures.json
packages/ckb-sdk-utils/__tests__/systemScripts/fixtures.json
packages/ckb-sdk-utils/__tests__/systemScripts/index.test.js
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-utils/src/address/index.ts
packages/ckb-sdk-utils/src/systemScripts.ts
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json
yarn.lock

* **core:** upgrade @ckb-lumos/indexer and add the example of sudt transaction ([c10ec0b](https://github.com/nervosnetwork/ckb-sdk-js/commit/c10ec0b95877e67599ee67306b1968934a5b55ca))
* **utils:** update acp lock script ([6d9a85f](https://github.com/nervosnetwork/ckb-sdk-js/commit/6d9a85f05f393216fc06650fd650f43049874a20))

chore: update package versions and changelogs

---

CHANGELOG.md
lerna.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/types/global.d.ts
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/package.json
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json

* **core:** fix the type declaration of changeLockScript ([23ad1db](https://github.com/nervosnetwork/ckb-sdk-js/commit/23ad1db7ca4fe9cc9011e5300a0a3efbfdb403ed))

fix(core): fix the type declaration of changeLockScript

---

.github/dependabot.yml
CHANGELOG.md
lerna.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/package.json
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/package.json
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json
yarn.lock

Release v0.41.1

---

package.json
packages/ckb-sdk-core/package.json
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/package.json
yarn.lock

1. remove lumos from optional deps
2. update typescript from rc to stable

chore: update deps

---

packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/__tests__/formatters/result.fixtures.json
packages/ckb-sdk-rpc/types/rpc/index.d.ts
packages/ckb-types/index.d.ts

A new field 'extension' is added to the block body
BREAKING CHANGE: A new field 'extension' is added to the block body
ref https://github.com/nervosnetwork/rfcs/pull/224

feat(rpc): a new field 'extension' is added to the block body

---

.github/workflows/bundle.yml
.gitignore
package.json
scripts/bundle-umd.sh

This commit adds a script to bundle umd packages instead of running commands in CI, and will include umd packages on publishing.

chore: add a script to bundle umd package

---

.github/workflows/bundle.yml
.gitignore
CHANGELOG.md
LICENSE
README.md
lerna.json
package.json
packages/ckb-sdk-core/CHANGELOG.md
packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/src/index.ts
packages/ckb-sdk-rpc/CHANGELOG.md
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-utils/CHANGELOG.md
packages/ckb-sdk-utils/package.json
packages/ckb-types/CHANGELOG.md
packages/ckb-types/package.json
packages/ckb-types/tsconfig.json
scripts/bundle-umd.sh
yarn.lock

1. add a detailed comment of `generateRawTransaction`
2. update copyright
3. add a script to bundle an umd package instead of running commands in CI

Release v0.102.1

---

packages/ckb-sdk-rpc/src/resultFormatter.ts

1. accept RPC.RawTransaction and return CKBComponent.RawTransaction
2. accept RPC.Transaction and return CKBComponent.Transaction

refactor: enhance type of ckb.rpc.resultFormatter.toTransaction

---

packages/ckb-sdk-utils/src/address/index.ts
packages/ckb-sdk-utils/src/calculateTransactionFee.ts
packages/ckb-sdk-utils/src/convertors/index.ts
packages/ckb-sdk-utils/src/crypto/blake160.ts
packages/ckb-sdk-utils/src/epochs.ts
packages/ckb-sdk-utils/src/index.ts
packages/ckb-sdk-utils/src/occupiedCapacity.ts
packages/ckb-sdk-utils/src/serialization/basic.ts
packages/ckb-sdk-utils/src/serialization/script.ts
packages/ckb-sdk-utils/src/serialization/transaction.ts
packages/ckb-sdk-utils/src/sizes.ts

- Fixed the issue that deprecated anno are displayed incorrectly on Vscode.
- Added migrate guide document link

Chore: optimize ckb-sdk-utils deprecated anno & add migrate guide link

---

.github/workflows/bundle.yml
.github/workflows/tests.yml
package.json
yarn.lock

1. add node.js@18, which is LTS;
2. remove node.js@12 and node.js@14, which are deprecated or
going to deprecate.

ci: update node versions

---

packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
packages/ckb-sdk-rpc/src/Base/index.ts
packages/ckb-sdk-rpc/src/Base/stats.ts

What problem does this PR solve?
------
As title.
ref:https://github.com/Magickbase/neuron-public-issues/issues/128
Check List
------
e2e Test
none

Fix: rename this rpc method

---

.github/workflows/tests.yml

Ref: 
- ⚠️ Deprecation of v1: https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1

ci: upgrade action of codecov to v3

---

.gitignore
package-lock.json
package.json
packages/ckb-sdk-core/package.json
packages/ckb-sdk-core/tsconfig.esm.json
packages/ckb-sdk-rpc/package.json
packages/ckb-sdk-rpc/src/index.ts
packages/ckb-sdk-rpc/src/method.ts
packages/ckb-sdk-rpc/tsconfig.esm.json
packages/ckb-sdk-utils/package.json
packages/ckb-sdk-utils/src/address/index.ts
packages/ckb-sdk-utils/tsconfig.esm.json

- Export ESM packages
- Support `data2` for CKB address
- Update RPC parameters data type to support `boolean`

Export ESM packages

---

README.md

Add an introduction and link to the CCC in README.

docs: add link to ccc sdk

---

packages/ckb-sdk-utils/__tests__/address/fixtures.json
packages/ckb-sdk-utils/src/address/index.ts

ref: https://github.com/ckb-js/ckb-sdk-js/issues/645

fix: fix data2 validation in 'isPayloadValid' method
